version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vigileye_db
    environment:
      POSTGRES_USER: vigileye
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vigileye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
